lti:
  issuer: "https://canvas.instructure.com"
  client-id: ${LTI_CLIENT_ID}
  jwks-url: "https://canvas.instructure.com/api/lti/security/jwks"
  allowed-clock-skew-seconds: 120
  validation-enabled: false

spring:
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  application:
    name: ${SPRING_APPLICATION_NAME}
  web:
    resources:
      static-locations: classpath:/static/
      cache-period: 3600

app:
  mocks:
    ags:
      enabled: true

server:
  port: ${SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    mappings:
      enabled: true